all: insertsort mergesort insertTime mergeTime

insertsort: insertsort.cpp
	g++ -Wall -std=c++11 insertsort.cpp -g -o insertsort

mergesort: mergesort.cpp
	g++ -Wall -std=c++11 mergesort.cpp -g -o mergesort

insertTime: insertTime.cpp
	g++ -Wall -std=c++11 insertTime.cpp -g -o insertTime

mergeTime: mergeTime.cpp
	g++ -Wall -std=c++11 mergeTime.cpp -g -o mergeTime

clean:
	rm insertsort mergesort insertTime mergeTime