all: stoogesort stoogeTime

stoogesort: stoogesort.cpp
	g++ -Wall -std=c++11 stoogesort.cpp -g -o stoogesort

stoogeTime: stoogeTime.cpp
	g++ -Wall -std=c++11 stoogeTime.cpp -g -o stoogeTime

clean:
	rm stoogesort stoogeTime